ex/ex/ex/urls.py
from django.contrib import admin
from django.urls import path, include

from ex import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('tables/', include('tables.urls', namespace='tables')),
    path('users/', include('users.urls', namespace='users')),
    
]

ex/ex/goods/urls.py
# from django.contrib import admin
from django.urls import path, include
from main import views


app_name = 'main'

urlpatterns = [
    path('', views.categories, name='categories'),
    path('product/', views.product, name='product'),
    
]

ex/ex/main/urls.py

from django.urls import path, include
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
]

ex/ex/goods/models.py
from django.db import models

# Create your models here.

ex/ex/main/models.py
from django.db import models

# Create your models here.

ex/ex/goods/views.py
from django.shortcuts import render

# Create your views here.

ex/ex/main/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index (request):
    context = {
        'title': 'Главная',
        
    }

    return render(request, 'main/index.html', context)

def contact (request):
    context = {
        'title': 'Контакты',
        
    }

    return render(request, 'main/contact.html', context)

ex/ex/main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    {% block css %}{% endblock css %}
</head>
<body>
    <header class="header">
        <a href="{% url 'main:index' %}">Главная</a>
        <a href="{% url 'main:contact' %}">Контакты</a>

        <a href="{% url 'users:login' %}">Логин</a>

        <a href="{% url 'tables:tables' %}">Форма</a>
        {% comment %} <a href="{% url 'tables:contact' %}">бронирование</a> {% endcomment %}
    </header>

    {% block content %}{% endblock content %}    
    
</body>
</html>

ex/ex/main/templates/main/contact.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}

    <h1>Контакты - наши контакты!!!</h1>

{% endblock content %}

ex/ex/main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}

    <h1>Главная - наша страничка</h1>

{% endblock content %}