reg/reg/goods/urls.py
from django.urls import path
from goods import views
app_name = 'goods'
urlpatterns = [
    path('', views.catalog, name='catalog'),
    path('<slug:slug>/', views.product, name='product'),
]

reg/reg/main/urls.py
from django.urls import path

from main import views
app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
]

reg/reg/goods/models.py
from django.db import models

# Create your models here.

class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'
    
    def __str__(self):
        return self.name
    

class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='goods_images',blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    
    
    brand = models.CharField(max_length=255, blank=True)
    year_of_production = models.IntegerField(blank=True, null=True)


    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория')

    class Meta:
        db_table = 'prodact'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name

    def display_id(self):
        return f"{self.id:05}"

reg/reg/main/models.py
from django.db import models

# Create your models here.

reg/reg/goods/views.py
# views.py
from django.shortcuts import render, get_object_or_404
from .models import Products, Categories

def catalog(request):
    # Получаем все продукты, которые есть в наличии
    products = Products.objects.filter(quantity__gt=0)

    # Сортировка
    sort = request.GET.get('sort', 'newest')  # По умолчанию по новизне

    if sort == 'year_desc':
        products = products.order_by('-year_of_production')
    elif sort == 'year_asc':
        products = products.order_by('year_of_production')
    elif sort == 'name_asc':
        products = products.order_by('name')
    elif sort == 'name_desc':
        products = products.order_by('-name')
    elif sort == 'price_asc':
        products = products.order_by('price')
    elif sort == 'price_desc':
        products = products.order_by('-price')
    else:
        products = products.order_by('-id')  # По новизне

    # Фильтрация по категориям
    category_slug = request.GET.get('category')
    if category_slug:
        products = products.filter(category__slug=category_slug)

    categories = Categories.objects.all()

    return render(request, 'goods/catalog.html', {'products': products, 'categories': categories})



# def product(request, slug):
#     product = get_object_or_404(Products, slug=slug)
    # return render(request, 'goods/product.html', {'product': product})

# def product(request, slug):

#     product = Products.objects.get(slug=slug)

#     context = {
#         'product': product
#     }

#     return render(request, 'goods/product.html', context)

def product(request, slug):
    product = Products.objects.get(slug=slug)

    context = {
        'product': product
    }

    return render(request, 'goods/product.html', context)

reg/reg/main/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index (request):
    context = {
        'title': 'Главная',
        'content': ['Aроматы', 'Ручной работы'],
        'words':['Выберите аромат'],
    }

    return render(request, 'main/index.html', context)



def contact(request):
    context = {
        'title': 'Контакты',
        'content': ['Контактные данные'],
        'words':['ПОЗВОНИТЕ НАМ','НАПИШИТЕ НАМ','НАЙДИТЕ НАС',],
    }

    return render(request, 'main/contact.html', context)

reg/reg/goods/templates/goods/catalog.html
{% extends "main/base.html" %}
{% load static %}



{% block css %}
<style>
/* Основные стили для каталога */
body {
    padding: 20px;
}

h1 {
    text-align: center;
    color: #333;
}

h2 {
    color: #555;
    border-bottom: 2px solid #ddd;
    padding-bottom: 10px;
}

ul {
    list-style-type: none;
    padding: 0;
}

ul li {
    margin: 5px 0;
}

ul li a {
    text-decoration: none;
    color: #007bff;
}

ul li a:hover {
    text-decoration: underline;
}

/* Стили для сортировки */
div > a {
    margin-right: 15px;
    color: #007bff;
}

div > a:hover {
    text-decoration: underline;
}

.product-list {
    display: flex;
    flex-wrap: wrap; /* Позволяет переносить товары на новую строку */
    justify-content: space-evenly; /* Распределяет товары по ширине */
}

/* Настройка карточек товаров */
.product-card {
    flex: 1 1 calc(25% - 20px); /* Каждый товар занимает 25% ширины контейнера минус отступы */
    margin: 10px; /* Отступы между карточками */
    max-width: 300px; /* Ограничение максимальной ширины карточки */
}

.product-card:hover {
    transform: scale(1.05);
}

/* Изображения товаров */
.product-card img {
    max-width: 100%;
    height: auto;
    border-radius: 4px;
}

/* Стили для наименования и цены товара */
.product-name {
    font-size: 1.2em;
    color: #333;
}

.product-price {
    font-size: 1.1em;
    color: #28a745; /* Зеленый цвет для цены */
}

/* Адаптивность */
@media (max-width: 768px) {
    .product-card {
        margin: 10px;
        padding: 10px;
    }

    h1, h2 {
        font-size: 1.5em;
    }
}
</style>
{% endblock css %}

{% block content %}
  
<h1>Каталог товаров</h1>

<div>
    <h2>Фильтр по категориям</h2>
    <ul>
        {% for category in categories %}
            <li><a href="?category={{ category.slug }}">{{ category.name }}</a></li>
        {% endfor %}
    </ul>
</div>

<div>
    <h2>Сортировка</h2>
    <a href="?sort=newest">По новизне</a> |
    <a href="?sort=year_desc">По году (спадание)</a> | 
    <a href="?sort=year_asc">По году (возрастание)</a> | 
    <a href="?sort=name_asc">По наименованию (А-Я)</a> | 
    <a href="?sort=name_desc">По наименованию (Я-А)</a> | 
    <a href="?sort=price_asc">По цене (низкая-высокая)</a> | 
    <a href="?sort=price_desc">По цене (высокая-низкая)</a> 
</div>






<div class="product-list">
    {% for product in products %}
        <div class="product-card">
            <a href="{% url 'goods:product' product.slug %}">
                {% if product.image %}
                    <img src="{{ product.image.url }}" alt="{{ product.name }}">
                {% else %}
                    <img src="{% static 'main/static/img/no-product.png' %}" alt="{{product.name}}">
                {% endif %}
                <h3 class="product-name">{{ product.name }}</h3>
                <p class="product-price">Цена: {{ product.price }}₽</p>
            </a>
        </div>
    {% endfor %}
</div>

{% endblock %}

reg/reg/goods/templates/goods/product.html
{% extends "main/base.html" %}
{% load static %}

{% block css %}
<style>
  /* Стиль для карточки товара */
.product-details {
  display: flex;
  gap: 20px; /* Пространство между изображением и информацией */
  margin-bottom: 30px; /* Отступ снизу */
}

.product-image {
  width: 50%; /* Ширина изображения */
  height: 50%; /* Высота изображения */
}

.product-image img {
  width: 90%; /* Заполнить всю ширину контейнера */
  height: 90%; /* Заполнить всю высоту контейнера */
  object-fit: cover; /* Покрыть всю область, обрезая лишнее */
}

.product-info {
  display: flex;
  flex-direction: column; /* Элементы будут располагаться вертикально */
  gap: 10px; /* Пространство между элементами */
}

.price {
  font-size: 20px; /* Размер шрифта для цены */
  font-weight: bold; /* Жирный шрифт для цены */
  color: #333; /* Цвет текста для цены */
}

h4 {
  margin-top: 20px; /* Отступ сверху для заголовка "Характеристики" */
}

ul {
  list-style: none; /* Убрать маркеры списка */
  padding: 0; /* Убрать отступ у списка */
}

li {
  margin-bottom: 5px; /* Отступ снизу для элементов списка */
}

button {
  background-color: #4CAF50; /* Цвет фона кнопки */
  color: white; /* Цвет текста кнопки */
  padding: 10px 20px; /* Отступы внутри кнопки */
  border: none; /* Убрать рамку кнопки */
  border-radius: 5px; /* Закругленные углы кнопки */
  cursor: pointer; /* Указать, что кнопка является кликабельной */
  font-size: 16px; /* Размер шрифта кнопки */
  transition: background-color 0.3s; /* Плавное изменение цвета при наведении */
}

button:hover {
  background-color: #45a049; /* Цвет фона при наведении */
}


</style>
{% endblock css %}

{% block content %}
<h2>{{ product.name }}</h2>

<div class="product-details">
  <div class="product-image">
    {% if product.image %}
      <img src="{{ product.image.url }}" alt="{{ product.name }}">
    {% else %}
      <img src="{% static 'default_product_image.jpg' %}" alt="{{ product.name }}">
    {% endif %}
  </div>

  <div class="product-info">
    <p class="price">{{ product.price|floatformat:2 }} руб.</p>
    <p>{{ product.description }}</p>
    <h4>Характеристики:</h4>
    <ul>
      <li>Бренд: {{ product.brand }}</li>
      <li>Год выпуска: {{ product.year_of_production }}</li>
      <li>Модель: {{ product.name }}</li>
    </ul>
    <button>В корзину</button>
  </div>
</div>
{% endblock %}

reg/reg/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
        {% block css %}{% endblock css %}
    
    <style>
      a {
        text-decoration: none;
        color: #333;
      }

    </style>
</head>
<body style="width: 100%; height: 100%;">
    <header class="menu" style="width: 90%; height: 30%; display: flex; justify-content: space-around; margin: 1% auto; align-items: center;">
      
      <div class="logo" style="width: 20%; height: 100%; ">
          <a href="{% url 'main:index' %}" style="margin-left: auto; margin-right: auto;  display: flex; flex-direction: column; justify-content: center; align-items: center;">
            <img src="{% static 'img/logotip.png' %}" width="15%" height="auto">
            <h1 style="font-size: smaller; margin: 0; font-weight: bolder;">Красота Волос</h1>
            <h2 style="font-size: smaller; margin: 0;">все для парикмахеров</h2>
          </a>
      </div>

      <div style="display: flex; justify-content: space-around; align-items: center; width: 70%;">
        <div class="pan" style="display: flex; align-items: center; justify-content: space-evenly; width: 35%;"> <!--lincs-->
          <a href="{% url 'main:index' %}" style="margin-right: 5%;"><p1>Главная</p1></a>
          <a href="{% url 'goods:catalog' %}" style="margin-right: 5%;"><p1>Каталог</p1></a>
          <a href="{% url 'main:contact' %}"><p1>Контакты</p1></a>

          
        </div>

        
          
        <!-- {% if user.is_authenticated %}
    <a href="#" class="btn btn-primary">Профиль</a>
{% else %}
    <a href="{% url 'users:register' %}" class="btn btn-secondary">Регистрация</a>
    <a href="{% url 'users:login' %}" class="btn btn-secondary">Авторизация</a>
{% endif %} -->

          <div>
            {% if user.is_authenticated %}
              <div>
                <h1>Добро пожаловать, {{ user.username }}!</h1>
                <a href="#" class="btn btn-secondary">Профиль</a>
                <a href="{% url 'users:logout' %}" class="btn btn-secondary">Выход</a>
              </div>
            {% else %}
              <div style="display: flex; justify-content: space-around; align-items: center; margin-left: 1%; ">   
                <a href="{% url 'users:login' %}" class="btn btn-secondary" style="margin-right: 3%;">Авторизация</a>
                <a href="{% url 'users:register' %}" class="btn btn-secondary">Регистрация</a>
              </div> 
            {% endif %}
          </div>

          
      
    
 

        
    </div>

    
    </header>

    <hr style="width: 93%; height: 0.1vw; background: #000000; margin-left: auto; margin-right: auto;">
    {% block content %}
    
    {% endblock content %}
    

    <footer style="background-color: #333; color: white; text-align: center; padding: 1%; margin-top: 1%;">
      <div class="container" style="display: flex; justify-content: space-between; align-items: center; align-content: center; margin: 2% 0;">
        <div>
          <p style="margin: 0; padding: 0;">Наша миссия, изменить выбор, Ваш выбор инструментов к лучшему.</p>
          <p style="margin: 0; padding: 0;">При отправке своих персональных данных вы даете согласие на их обработку.</p>
        </div>

        <div style="margin-bottom: 1%;">
          <p style="margin: 0; padding: 0;">Следите за нами в социальных сетях:</p>
          <a href="https://www.facebook.com" target="_blank" style="color: white; margin: 0 10px;">Facebook</a>
          <a href="https://www.instagram.com" target="_blank" style="color: white; margin: 0 10px;">Instagram</a>
          <a href="https://www.twitter.com" target="_blank" style="color: white; margin: 0 10px;">Twitter</a>
        </div>
      </div>
      <p style="margin: 0; padding: 0; text-align: left; font-size: xx-small;">© 2023 Магазин Парикмахерских Товаров. Все права защищены.</p>
  </footer>
  

    
   
    

    {% block js %}
    
    {% endblock js %}
    
</body>
</html>

reg/reg/main/templates/main/contact.html
{% extends "main/base.html" %}
{% load static %}

    {% block css %}
    
    {% endblock css %}


    {% block content %}

    <header>
        <h1 style="text-align: center;">Контакты</h1>
    </header>

    <div style="position: relative; width: 100%;">
        <img src="{% static 'img/map.png' %}" style="width: 100%; height: auto;" alt="..." >

        <div style="position: absolute; top: 5%; left: 55%; color: white; background-color: rgba(0, 0, 0, 0.5); padding: 10px; width: 30%;">
            <h2>Наш офис</h2>

            <div class="contact-info" style="background: white; border: 1px solid black; width: 100%; margin-bottom: 10px; color: black; padding-left: 5%;">
                <br>
                <p style="margin: 0;">10:00 - 20:00</p>
                <h3 style="margin: 0; font-weight: 400; font-size: x-large;">Москва, ул. Примерная, д. 1</h3>
                <br>
                <p style="margin: 0;">Телефон</p>
                <h3 style="margin: 0; font-weight: 400; font-size: x-large;">+7 (123) 456-78-90</h3>
                <br>
                <p style="margin: 0;">E-mail</p>
                <h3 style="margin: 0; font-weight: 400; font-size: x-large;">info@parikmaherskie.ru</h3><br>
            </div>
        </div>
    </div>
    
    <h2 style="margin-left: 5%; margin-bottom: 2%; text-align: center;">Наши магазины</h2>

    <div class="container" style="display: flex; flex-wrap: wrap; width: 100%; justify-content: space-around; margin-left: auto; margin-right: auto;">

        
    
        <div class="contact-info" style="background: darkgrey; border: 1px solid black; width: 33%; margin-bottom: 10px; padding: 3%;">
            <p><strong>Адрес:</strong> ул. Примерная, д. 1, Москва, Россия</p>
            <p><strong>Телефон:</strong> +7 (123) 456-78-90</p>
            <p><strong>Email:</strong> info@parikmaherskie.ru</p>
        </div>
    
        <div class="contact-info" style="background: darkgrey; border: 1px solid black; width: 33%; margin-bottom: 10px; padding: 3%;">
            <p><strong>Адрес:</strong> ул. Первомайская, д. 103, Санкт-Петербург, Россия</p>
            <p><strong>Телефон:</strong> +7 (800) 555-35-35</p>
            <p><strong>Email:</strong> info@parikmaherskiepeter.ru</p>
        </div>
        
        <div class="contact-info" style="background: darkgrey; border: 1px solid black; width: 33%; margin-bottom: 10px; padding: 3%;">
            <p><strong>Адрес:</strong> ул. Азовская, д. 456, Ростов-на-Дону, Россия</p>
            <p><strong>Телефон:</strong> +7 (980) 980-98-90</p>
            <p><strong>Email:</strong> info@parikmaherskierostov.ru</p>
        </div>
    </div>
    

    {% endblock content %}




 
    
{% block js %}

   
{% endblock js %}


reg/reg/main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

    {% block css %}
    
    {% endblock css %}


    {% block content %}
     
    <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'img/mailsl.png' %}" class="d-block w-100" alt="..." >
          </div>
          <div class="carousel-item">
            <img src="{% static 'img/tsale.png' %}" class="d-block w-100" alt="..." >
          </div>
          <div class="carousel-item">
            <img src="{% static 'img/sale.png' %}" class="d-block w-100" alt="..." >
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
        
    {% endblock content %}




 
    
{% block js %}

   
{% endblock js %}
